/** Every UI surface category used in production React Native mobile apps */
export interface RNPatternGroup {
  id: string;
  title: string;
  description: string;
  items: string[];
}

export const RN_MOBILE_PATTERN_GROUPS: RNPatternGroup[] = [
  {
    id: 'core',
    title: 'Core & layout',
    description: 'Foundation primitives every app needs.',
    items: [
      'SafeAreaView',
      'KeyboardAvoidingView',
      'ScrollView',
      'FlatList',
      'SectionList',
      'VirtualizedList',
      'Pressable',
      'View / Text',
      'Image',
      'ActivityIndicator',
      'StatusBar',
      'Modal',
      'RefreshControl',
    ],
  },
  {
    id: 'navigation',
    title: 'Navigation',
    description: 'React Navigation and native routing patterns.',
    items: [
      'Stack navigator',
      'Tab navigator',
      'Drawer navigator',
      'Native stack',
      'Bottom tabs',
      'Top tabs',
      'Header large title',
      'Deep linking',
      'Universal links',
      'Back gesture',
    ],
  },
  {
    id: 'inputs',
    title: 'Inputs & forms',
    description: 'Data entry and validation flows.',
    items: [
      'TextInput',
      'Secure text entry',
      'OTP / PIN',
      'Picker',
      'Date/time picker',
      'Switch',
      'Checkbox',
      'Radio',
      'Slider',
      'Autocomplete',
      'Form validation',
      'Submit states',
    ],
  },
  {
    id: 'feedback',
    title: 'Feedback & states',
    description: 'Loading, empty, and error experiences.',
    items: [
      'Toast / Snackbar',
      'Alert',
      'Banner',
      'Skeleton loaders',
      'Empty states',
      'Error boundaries',
      'Pull-to-refresh',
      'Infinite scroll',
      'Progress indicators',
      'Haptic feedback',
    ],
  },
  {
    id: 'overlays',
    title: 'Overlays & sheets',
    description: 'Transient UI layered above content.',
    items: [
      'Bottom sheet',
      'Action sheet',
      'Alert dialog',
      'Popover',
      'Tooltip',
      'Full-screen modal',
      'Half modal',
      'Context menu',
      'Share sheet',
      'Permission prompt',
    ],
  },
  {
    id: 'gestures',
    title: 'Gestures & motion',
    description: 'Gesture Handler + Reanimated interactions.',
    items: [
      'Pan gesture',
      'Pinch zoom',
      'Swipeable rows',
      'Drag & drop',
      'Long press',
      'Double tap',
      'Spring animations',
      'Shared element transitions',
      'Layout animations',
      'Parallax scroll',
    ],
  },
  {
    id: 'media',
    title: 'Media & device',
    description: 'Camera, maps, and native capabilities.',
    items: [
      'Camera',
      'Image picker',
      'Video player',
      'Maps (MapView)',
      'Geolocation',
      'Push notifications',
      'Biometrics',
      'Clipboard',
      'Share API',
      'WebView',
      'Bluetooth / NFC',
    ],
  },
  {
    id: 'commerce',
    title: 'Commerce & fintech',
    description: 'Shopping, payments, and wallets.',
    items: [
      'Product grid',
      'Cart',
      'Checkout',
      'Payment sheet',
      'Order history',
      'Wallet balance',
      'QR pay',
      'Subscriptions',
      'Receipts',
      'Coupons',
    ],
  },
  {
    id: 'social',
    title: 'Social & content',
    description: 'Feeds, chat, and profiles.',
    items: [
      'Feed timeline',
      'Stories',
      'Comments',
      'Chat bubbles',
      'Typing indicator',
      'Reactions',
      'User profile',
      'Follow / block',
      'Media carousel',
      'Rich link previews',
    ],
  },
  {
    id: 'system',
    title: 'System & settings',
    description: 'OS integration and preferences.',
    items: [
      'Settings list',
      'Toggle rows',
      'Theme (light/dark)',
      'Language picker',
      'Notification prefs',
      'Privacy controls',
      'App version',
      'Logout',
      'Rate app',
      'Support / FAQ',
    ],
  },
];

export const RN_PATTERN_COUNT = RN_MOBILE_PATTERN_GROUPS.reduce(
  (sum, g) => sum + g.items.length,
  0,
);
